### ISSUE TITLE
Feature request: Add support for Command line arguments.

### ISSUE THREAD

**Issue by masterashu** [masterashu/TestCaseGenerator#2]

**Comment by dkapur17** [comment]
I would like to take up this assignment! TIA!

**Comment by dkapur17** [comment]
Completed! Will proceed with PR on 1st October. #hactoberfest

**Comment by masterashu** [comment]
Good!

**Comment by dkapur17** [comment]
So can I make a PR to regarding this issue without being assigned?

**Comment by masterashu** [comment]
Yes, you can. Also a valid PR is eligible for hactoberfest. It doesn't need to merged. [read more here](https://hacktoberfest.digitalocean.com/details#participation-rules)
